export const TOGGLE_NAV = "TOGGLE_NAV";
export const TOGGLE_CONTACT = "TOGGLE_CONTACT";
export const TOGGLE_RESERVATION = "TOGGLE_RESERVATION";
export const SAVE_RESERVATION = "SAVE_RESERVATION";
export const SAVE_RESERVATION_SUCCES = "SAVE_RESERVATION_SUCCES";
